export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const LOAD_COURSES_SUCCESSS = 'LOAD_COURSES_SUCCESSS';
export const LOAD_AUTHORS_SUCCESSS = 'LOAD_AUTHORS_SUCCESSS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
